name: build and deploy static website to s3

on:
  push:
    branches:
      - main    
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "build step"

  deploy:
    if: github.event_name == 'push' && github.event.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "deploy step"
